const Food = require('../models/Food');

const seededFoods = [
  {
    name: 'Poha',
    description: 'Light and tangy poha with peanuts, coriander, and lemon for a perfect breakfast.',
    category: 'Breakfast',
    price: 40,
    image: 'https://source.unsplash.com/featured/1200x800/?poha',
    available: true,
    stock: 30,
    prepTime: '8-10 min',
    isVeg: true,
    isSpecial: true,
    isBestseller: true,
  },
  {
    name: 'Idli Sambar',
    description: 'Soft idlis paired with hot sambar and coconut chutney.',
    category: 'South Indian',
    price: 55,
    image: 'https://source.unsplash.com/featured/1200x800/?idli-sambar',
    available: true,
    stock: 25,
    prepTime: '10-12 min',
    isVeg: true,
    isSpecial: true,
    isBestseller: true,
  },
  {
    name: 'Masala Dosa',
    description: 'Crispy dosa served with sambar and coconut chutney, a campus favorite.',
    category: 'South Indian',
    price: 60,
    image: 'https://source.unsplash.com/featured/1200x800/?masala-dosa',
    available: true,
    stock: 20,
    prepTime: '12-15 min',
    isVeg: true,
    isSpecial: true,
    isBestseller: true,
  },
  {
    name: 'Aloo Paratha',
    description: 'Stuffed potato paratha served with butter, curd, and pickle.',
    category: 'Breakfast',
    price: 50,
    image: 'https://source.unsplash.com/featured/1200x800/?aloo-paratha',
    available: true,
    stock: 22,
    prepTime: '12-14 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Samosa',
    description: 'Crispy potato and pea samosa served with green chutney.',
    category: 'Snacks',
    price: 25,
    image: 'https://source.unsplash.com/featured/1200x800/?samosa',
    available: true,
    stock: 40,
    prepTime: '6-8 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Paneer Wrap',
    description: 'Soft roti filled with spiced paneer, lettuce, and mint chutney.',
    category: 'Snacks',
    price: 75,
    image: 'https://source.unsplash.com/featured/1200x800/?paneer-wrap',
    available: true,
    stock: 18,
    prepTime: '8-10 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Paneer Sandwich',
    description: 'Grilled paneer sandwich with tomato, lettuce, and spicy mayo.',
    category: 'Meals',
    price: 85,
    image: 'https://source.unsplash.com/featured/1200x800/?paneer-sandwich',
    available: true,
    stock: 20,
    prepTime: '10-12 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Veg Burger',
    description: 'Juicy veg patty with lettuce, tomato, and special sauce in a soft bun.',
    category: 'Meals',
    price: 90,
    image: 'https://source.unsplash.com/featured/1200x800/?veg-burger',
    available: true,
    stock: 18,
    prepTime: '10-12 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Pav Bhaji',
    description: 'Spicy bhaji served with buttered pav and onion salad.',
    category: 'Meals',
    price: 95,
    image: 'https://source.unsplash.com/featured/1200x800/?pav-bhaji',
    available: true,
    stock: 16,
    prepTime: '12-15 min',
    isVeg: true,
    isSpecial: true,
    isBestseller: true,
  },
  {
    name: 'Chole Bhature',
    description: 'Spiced chickpeas served with fluffy fried bhature.',
    category: 'Meals',
    price: 85,
    image: 'https://source.unsplash.com/featured/1200x800/?chole-bhature',
    available: true,
    stock: 18,
    prepTime: '12-15 min',
    isVeg: true,
    isSpecial: true,
    isBestseller: true,
  },
  {
    name: 'Veg Pulao',
    description: 'Aromatic rice cooked with peas, carrots, and mild spices.',
    category: 'Meals',
    price: 80,
    image: 'https://source.unsplash.com/featured/1200x800/?veg-pulao',
    available: true,
    stock: 18,
    prepTime: '12-14 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Veg Fried Rice',
    description: 'Wok-tossed rice with mixed vegetables and savory aromatics.',
    category: 'Chinese',
    price: 100,
    image: 'https://source.unsplash.com/featured/1200x800/?vegetable-fried-rice',
    available: true,
    stock: 20,
    prepTime: '12-15 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Hakka Noodles',
    description: 'Stir-fried noodles with crunchy vegetables and light soy seasoning.',
    category: 'Chinese',
    price: 95,
    image: 'https://source.unsplash.com/featured/1200x800/?hakka-noodles',
    available: true,
    stock: 22,
    prepTime: '10-12 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Veg Momos',
    description: 'Steamed vegetable momos served with spicy chili sauce.',
    category: 'Chinese',
    price: 85,
    image: 'https://source.unsplash.com/featured/1200x800/?vegetable-momos',
    available: true,
    stock: 24,
    prepTime: '10-12 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'French Fries',
    description: 'Crispy golden fries seasoned with salt and pepper.',
    category: 'Snacks',
    price: 50,
    image: 'https://source.unsplash.com/featured/1200x800/?french-fries',
    available: true,
    stock: 28,
    prepTime: '6-8 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Maggi',
    description: 'Classic masala Maggi noodles with vegetables and a dash of chili.',
    category: 'Snacks',
    price: 40,
    image: 'https://source.unsplash.com/featured/1200x800/?maggi-noodles',
    available: true,
    stock: 35,
    prepTime: '5-8 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Paneer Tikka Roll',
    description: 'Grilled paneer tikka wrapped in a soft roti with chutney.',
    category: 'Meals',
    price: 105,
    image: 'https://source.unsplash.com/featured/1200x800/?paneer-tikka-roll',
    available: true,
    stock: 14,
    prepTime: '12-14 min',
    isVeg: true,
    isSpecial: true,
    isBestseller: true,
  },
  {
    name: 'Cold Coffee',
    description: 'Iced coffee blended with milk and topped with whipped cream.',
    category: 'Beverages',
    price: 70,
    image: 'https://source.unsplash.com/featured/1200x800/?cold-coffee',
    available: true,
    stock: 22,
    prepTime: '4-5 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Lassi',
    description: 'Refreshing sweet lassi with a hint of cardamom.',
    category: 'Beverages',
    price: 65,
    image: 'https://source.unsplash.com/featured/1200x800/?lassi',
    available: true,
    stock: 18,
    prepTime: '3-4 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Tea',
    description: 'Hot masala tea brewed with milk, spices, and sugar.',
    category: 'Beverages',
    price: 25,
    image: 'https://source.unsplash.com/featured/1200x800/?tea',
    available: true,
    stock: 35,
    prepTime: '3-4 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Coffee',
    description: 'Hot coffee perfect for early morning lectures.',
    category: 'Beverages',
    price: 35,
    image: 'https://source.unsplash.com/featured/1200x800/?coffee',
    available: true,
    stock: 30,
    prepTime: '3-4 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Gulab Jamun',
    description: 'Soft syrup-soaked gulab jamun for a sweet finish.',
    category: 'Desserts',
    price: 50,
    image: 'https://source.unsplash.com/featured/1200x800/?gulab-jamun',
    available: true,
    stock: 20,
    prepTime: '5-7 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Jalebi',
    description: 'Crispy spirals of jalebi soaked in sweet saffron syrup.',
    category: 'Desserts',
    price: 45,
    image: 'https://source.unsplash.com/featured/1200x800/?jalebi',
    available: true,
    stock: 18,
    prepTime: '5-7 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Brownie',
    description: 'Warm chocolate brownie with a fudgy center.',
    category: 'Desserts',
    price: 70,
    image: 'https://source.unsplash.com/featured/1200x800/?brownie',
    available: true,
    stock: 14,
    prepTime: '5-7 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Dahi Puri',
    description: 'Crispy puris filled with potato, yogurt, and chutney.',
    category: 'Snacks',
    price: 45,
    image: 'https://source.unsplash.com/featured/1200x800/?dahi-puri',
    available: true,
    stock: 20,
    prepTime: '5-7 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Veg Thali',
    description: 'A college-style veg thali with dal, sabzi, rice, chapati, and salad.',
    category: 'Meals',
    price: 120,
    image: 'https://source.unsplash.com/featured/1200x800/?veg-thali',
    available: true,
    stock: 16,
    prepTime: '15-18 min',
    isVeg: true,
    isSpecial: true,
    isBestseller: true,
  },
  {
    name: 'Rajma Chawal',
    description: 'Comforting rajma curry served with steamed basmati rice.',
    category: 'Meals',
    price: 95,
    image: 'https://source.unsplash.com/featured/1200x800/?rajma-chawal',
    available: true,
    stock: 18,
    prepTime: '14-16 min',
    isVeg: true,
    isSpecial: true,
    isBestseller: true,
  },
  {
    name: 'Dal Makhani',
    description: 'Creamy black lentils cooked with butter and spice.',
    category: 'Meals',
    price: 90,
    image: 'https://source.unsplash.com/featured/1200x800/?dal-makhani',
    available: true,
    stock: 20,
    prepTime: '13-15 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Paneer Butter Masala',
    description: 'Soft paneer cubes simmered in a rich tomato and butter gravy.',
    category: 'Meals',
    price: 140,
    image: 'https://source.unsplash.com/featured/1200x800/?paneer-butter-masala',
    available: true,
    stock: 14,
    prepTime: '14-16 min',
    isVeg: true,
    isSpecial: true,
    isBestseller: true,
  },
  {
    name: 'Chana Masala',
    description: 'Spicy chickpea curry cooked with onions, tomatoes, and garam masala.',
    category: 'Meals',
    price: 80,
    image: 'https://source.unsplash.com/featured/1200x800/?chana-masala',
    available: true,
    stock: 20,
    prepTime: '12-14 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Bread Pakora',
    description: 'Crispy fried bread pakora stuffed with spicy potato filling.',
    category: 'Snacks',
    price: 35,
    image: 'https://source.unsplash.com/featured/1200x800/?bread-pakora',
    available: true,
    stock: 28,
    prepTime: '6-8 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Veg Cutlet',
    description: 'Spiced vegetable cutlets served hot with mint chutney.',
    category: 'Snacks',
    price: 45,
    image: 'https://source.unsplash.com/featured/1200x800/?vegetable-cutlet',
    available: true,
    stock: 26,
    prepTime: '8-10 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Corn Chaat',
    description: 'Tangy corn chaat tossed with onions, coriander, and chaat masala.',
    category: 'Snacks',
    price: 50,
    image: 'https://source.unsplash.com/featured/1200x800/?corn-chaat',
    available: true,
    stock: 22,
    prepTime: '5-7 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Aloo Tikki',
    description: 'Pan-fried potato tikki served with chutneys and onions.',
    category: 'Snacks',
    price: 35,
    image: 'https://source.unsplash.com/featured/1200x800/?aloo-tikki',
    available: true,
    stock: 24,
    prepTime: '6-8 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Veg Spring Roll',
    description: 'Crispy spring rolls stuffed with mixed vegetables and sauce.',
    category: 'Chinese',
    price: 65,
    image: 'https://source.unsplash.com/featured/1200x800/?spring-roll',
    available: true,
    stock: 20,
    prepTime: '8-10 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Gobi Manchurian',
    description: 'Crispy cauliflower florets tossed in tangy Indo-Chinese sauce.',
    category: 'Chinese',
    price: 90,
    image: 'https://source.unsplash.com/featured/1200x800/?gobi-manchurian',
    available: true,
    stock: 18,
    prepTime: '12-14 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Masala Chai',
    description: 'Hot spiced tea brewed with milk, ginger, and cardamom.',
    category: 'Beverages',
    price: 20,
    image: 'https://source.unsplash.com/featured/1200x800/?masala-chai',
    available: true,
    stock: 40,
    prepTime: '3-4 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Nimbu Pani',
    description: 'Fresh lemonade with mint and a pinch of salt.',
    category: 'Beverages',
    price: 30,
    image: 'https://source.unsplash.com/featured/1200x800/?lemonade',
    available: true,
    stock: 35,
    prepTime: '2-3 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Rasmalai',
    description: 'Soft cheese dumplings soaked in sweet cardamom milk.',
    category: 'Desserts',
    price: 55,
    image: 'https://source.unsplash.com/featured/1200x800/?rasmalai',
    available: true,
    stock: 18,
    prepTime: '5-7 min',
    isVeg: true,
    isSpecial: false,
    isBestseller: true,
  },
  {
    name: 'Paneer Tikka',
    description: 'Grilled paneer cubes marinated in spices and yogurt.',
    category: 'Snacks',
    price: 110,
    image: 'https://source.unsplash.com/featured/1200x800/?paneer-tikka',
    available: true,
    stock: 16,
    prepTime: '12-14 min',
    isVeg: true,
    isSpecial: true,
    isBestseller: true,
  },
];

const seedFoods = async () => {
  const count = await Food.countDocuments();
  if (count === 0) {
    await Food.insertMany(seededFoods);
    return;
  }

  for (const foodData of seededFoods) {
    await Food.findOneAndUpdate(
      { name: foodData.name },
      { $set: foodData },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
  }
};

module.exports = { seedFoods };
